### ISSUE TITLE
Pull request of another user aren't shown as menu items

### ISSUE THREAD

**Issue by winnier** [bswinnerton/launchbar-github#81]
<img width="668" alt="screen shot 2017-07-26 at 7 40 50 pm" src="https://user-images.githubusercontent.com/6155923/28648241-62c673e6-723a-11e7-9dc4-b275cdc9d04e.png">

**Comment by bswinnerton** [comment]
I think this might just be a result of you not being able to see any of that user's open pull requests. I'm going to close this out for now, but if it's still a problem feel free to reopen it ❤️.
